volumes:
  n8n_data:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    expose:
      - 5678
    volumes:
      - n8n_data:/home/node/
    environment:
      - N8N_HOST=n8n.carrasco.dev
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      # - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.carrasco.dev/
      # - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    networks:
      - default
      - proxy_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.carrasco.dev`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le
networks:
  proxy_default:
    external: true
